### ISSUE TITLE
[Meta issue] Create issues for components that need improved localisation

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#1288]
## Need to triage

- [x] Avatar (React) - _alt text is based on initials. Examples of weirdly longs names in Storybook already. No layout that needs RTL adjustments._
- [x] Badge (React)
- [x] Button (Zen) (React)
- [x] IconButton (React)
- [x] Card (React)
- [ ] Collapsible (React)
- [ ] Divider (React)
- [ ] Dropdown (React)
- [ ] EmptyState (React)
- [ ] FilterMenuButton (React)
- [ ] CheckboxField (React)
- [ ] CheckboxGroup (React)
- [ ] RadioField (React)
- [ ] TextAreaField (React)
- [ ] TextField (React)
- [ ] ToggleSwitchField (React)
- [ ] GuidanceBlock (React)
- [ ] HeroCard (React)
- [ ] HeroPanel (React)
- [ ] HierarchicalMenu (React)
- [ ] HierarchicalSelect (React)
- [ ] Illustration, Scene (React)
- [ ] Illustration, Spot (React)
- [ ] LikertScaleLegacy (React)
- [ ] LoadingPlaceholder (React)
- [ ] LoadingSpinner (React)
- [ ] Menu (React)
- [ ] Modal (React)
- [ ] PageLayout (React)
- [ ] RadioGroup (React)
- [ ] Popover (React)
- [ ] SearchBox (React)
- [ ] Select (React)
- [ ] SplitButton (React)
- [ ] Slider (React)
- [ ] Table (React)
- [ ] Tabs (React)
- [ ] Tag (React)
- [ ] Tile (React)
- [ ] TitleBlockZen (React)
- [ ] Tooltip (React)
- [ ] VerticalProgressIndicator (React)
- [ ] VerticalProgressStep (React)
- [ ] Well (React)
- [ ] ZenNavigationBar (React)
- [ ] Box (React)
- [ ] GlobalNotification (React)
- [ ] Heading (React)
- [ ] Icon (React)
- [ ] InlineNotification (React)
- [ ] Paragraph
- [ ] ToastNotification (React)
- [ ] Design Tokens/Story Board
- [ ] Button (Zen) (Elm)
- [ ] Card (Elm)
- [ ] Divider (Elm)
- [ ] EmptyState (Elm)
- [ ] CheckboxField (Elm)
- [ ] RadioField (Elm)
- [ ] TextAreaField (Elm)
- [ ] TextField (Elm)
- [ ] ToggleSwitchField (Elm)
- [ ] LoadingPlaceholder (Elm)
- [ ] Modal (Elm)
- [ ] Popover (Elm)
- [ ] SplitButton (Elm)
- [ ] Table (Elm)
- [ ] Tag (Elm)
- [ ] Tooltip (Elm)
- [ ] Well (Elm)
- [ ] Box (Elm)
- [ ] GlobalNotification (Elm)
- [ ] Heading (Elm)
- [ ] Icon (Elm)
- [ ] InlineNotification (Elm)
- [ ] Paragraph (Elm)
- [ ] ToastNotification (Elm)

## Need to remove hard coded strings

This component has UI that is hard coded in English and cannot be changed by a consuming application.

## Need to add right to left support

This component needs to adapt to a "RTL" context for languages like Hebrew and Arabic, but doesn't yet.

## Need to create a Storybook to show RTL and translated text

- [ ] Button (Zen) (React) - _show RTL example, perhaps with an arrow or chevron icon that changes direction. Translations of label and working label would also be good._
- [ ] Card (React)

We don't have an example in Storybook for how this component can use translated strings or switch to RTL.
