### ISSUE TITLE
All Modals require visual upgrades

### ISSUE THREAD

**Issue by katsambarcus** [cultureamp/kaizen-design-system#1469]
As mentioned in [this post](https://cultureamp.slack.com/archives/CETLTFG9G/p1619056402029500), there have been a host of improvements made to our `Confirmation`, `Input-Edit` and ~Information~ `Context Modals`.

- All Modals have had structural changes so they are now RTL-LTR friendly – no more centred text
- Confirmation Modals now have two visual options to choose from: Default (no spot animation) & Prominent (yes spot animation)
- Roadblock Modal is now just a regular old `Confirmation Modal` using the new `Assertive Mood` ([more info on the new moods](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/?node-id=1929%3A81))
- Information Modals are now called Context Modals

[UI Kit: Heart - Modal sticker sheet](https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/?node-id=1929%3A35439)

Happy to pair with an Engineer 🥑 , just let me know!

## Work breakdown

- [x] Break the work up into parts
- [x] InputModal [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2300)
- [x] ConfirmationModal (variants: default, prominent) [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2308/)
- [x] ContextModal (variants: portrait, landscape) [PR here](https://github.com/cultureamp/kaizen-design-system/pull/2323)
- [x] Update Storybook stories into 3 main sheets

**Comment by lijuenc** [comment]
Hey @katsambarcus. Since these updates also include layout changes, do we need to keep the Zen modal layouts too (and have two versions of Modals going, switching based on the currently active theme themes) or are we good to make this apply to all modals going forward?

**Comment by katsambarcus** [comment]
@lijuenc 

Good question. In my mind, I was hoping we could update all modals that currently exist in Kaizen to reflect this new direction so that existing modals in product will benefit from the improvements for LTR-RTL layouts.

As for Zen v Heart themes. I imagine we continue to work with existing Zen modals, and when we make the switch in product, we'll get the Heart theme for free?

**Comment by lijuenc** [comment]
>update all modals that currently exist in Kaizen to reflect this new direction

Yeah, this would make things simpler as well so we won't have to maintain two distinct layouts (which adds more complexity than the other theme elements like colours and spacing which can be switched by swapping design-tokens values).

>As for Zen v Heart themes. I imagine we continue to work with existing Zen modals, and when we make the switch in product, we'll get the Heart theme for free?

Yeah, for colours, spacing and illustrations, that will be the case.

**Comment by katsambarcus** [comment]
A recent addition to the Context Modal has been made to the UI Kit, allowing for illustration compositions (Landscape or Portrait to fit neatly into the modal's layout.

![image](https://user-images.githubusercontent.com/15222341/138186397-137e35d6-f4b0-4f9e-be51-fbe14cf1da65.png)

**Comment by katsambarcus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Portrait / Landscape variants for Context Modal](https://trello.com/c/UyApia61/499-create-portrait-landscape-variants-for-context-modal)

**Comment by NatalieLoyzaga** [comment]
Hey @katsambarcus, Im slowing making my way through the new designs/variants. I have a few follow up questions regarding the designs...

- Is there still a Positive and Negative (red button) Input-Edit modal?
- Does each modal require a RTL version and therefore another design layout?
- How did you want the modals to look when on mobile (especially the prominent variants)? 

Thanks!

**Comment by katsambarcus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Responsive: Modals](https://trello.com/c/djoTUsns/522-responsive-modals)
