### ISSUE TITLE
Run Chromatic using the Chromatic github action (+ switch to Culture Amp account)

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1602]
## TODO:
- [x] create a Chromatic project for Kaizen in the Culture Amp Chromatic account
- [x] add a `chromatic.yaml` file to `.github/workflows` that runs the official Chromatic github action
- [x] make chromatic builds opt-in per commit (the default is to run the on every commit, which would quickly eat up all of our credits)
- [ ] delete the old buildkite chromatic step that was linked to a chromatic project on Michael's chromatic account.

**Comment by mbylstra** [comment]
We have started working on this in https://github.com/cultureamp/kaizen-design-system/pull/1601

**Comment by mbylstra** [comment]
I created a branched PR that adds the functionality where the action is only run if you add a comment "run chromatic": https://github.com/cultureamp/kaizen-design-system/pull/1603
